baseURL = 'https://nicoloboschi.com/'
languageCode = 'en-us'
title = 'Thinking out loud'
theme = 'chicago7'
pagination.pagerSize = 10

[permalinks]
posts = "/posts/:year:month:day"

[markup]
[markup.highlight]
style = "bw"
[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.header]]
name = "Home"
url = "/"
weight = 10

[[menu.header]]
name = "Posts"
url = "posts"
weight = 20

[params]
author = "Nicolo Boschi"

[params.social]
feed = "/index.xml"
